# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: experiences_spain 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "experiences_spain".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Luis Ciudad".freeze]
  s.date = "2018-02-09"
  s.description = "longer description of your gem".freeze
  s.email = "lciugar@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "experiences_spain.gemspec",
    "lib/experiences_spain.rb",
    "lib/experiences_spain/api_operations/find.rb",
    "lib/experiences_spain/api_operations/list.rb",
    "lib/experiences_spain/api_operations/save.rb",
    "lib/experiences_spain/api_operations/search.rb",
    "lib/experiences_spain/api_operations/translate.rb",
    "lib/experiences_spain/api_operations/validate.rb",
    "lib/experiences_spain/api_resource.rb",
    "lib/experiences_spain/client.rb",
    "lib/experiences_spain/experience.rb",
    "lib/experiences_spain/experience_not_found.rb",
    "lib/experiences_spain/image.rb",
    "lib/experiences_spain/resource.rb",
    "lib/experiences_spain/validation.rb",
    "lib/experiences_spain/version.rb",
    "lib/experiences_spain/video.rb",
    "spec/api/find_spec.rb",
    "spec/api/list_spec.rb",
    "spec/api/save_spec.rb",
    "spec/api/search_spec.rb",
    "spec/api/translate_spec.rb",
    "spec/api/validate_spec.rb",
    "spec/resources/experience_spec.rb",
    "spec/resources/image_spec.rb",
    "spec/resources/resource_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/stubbed_responses.rb",
    "spec/support/stubbed_responses.yml"
  ]
  s.homepage = "http://github.com/nanocity/experiences_spain".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.14".freeze
  s.summary = "Spain.info experiences API Client".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<facets>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<hashie>.freeze, [">= 0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<webmock>.freeze, [">= 0"])
    else
      s.add_dependency(%q<httparty>.freeze, [">= 0"])
      s.add_dependency(%q<facets>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<hashie>.freeze, [">= 0"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<webmock>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>.freeze, [">= 0"])
    s.add_dependency(%q<facets>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<hashie>.freeze, [">= 0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<webmock>.freeze, [">= 0"])
  end
end

